version: '3'

services:
  db:
    image: postgres
    container_name: db_api_notifly
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - ./data/db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    restart: always
    container_name: api_notifly
    command: 'npx prisma migrate dev && npm run start'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - 3333:3333
    depends_on:
      - db
